# Generated by Django 5.2.10 on 2026-01-24 15:06

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=255)),
                ('installation_id', models.CharField(blank=True, max_length=255)),
                ('private_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('webhook_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'GitHub Configuration',
                'verbose_name_plural': 'GitHub Configuration',
            },
        ),
        migrations.CreateModel(
            name='GooglePSEConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('search_engine_id', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Google PSE Configuration',
                'verbose_name_plural': 'Google PSE Configuration',
            },
        ),
        migrations.CreateModel(
            name='GraphAPIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, max_length=255)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Graph API Configuration',
                'verbose_name_plural': 'Graph API Configuration',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeaviateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Weaviate Configuration',
                'verbose_name_plural': 'Weaviate Configuration',
            },
        ),
        migrations.CreateModel(
            name='ZammadConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('api_token', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Zammad Configuration',
                'verbose_name_plural': 'Zammad Configuration',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Approver', 'Approver')], default='User', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveIntegerField()),
                ('verb', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Planned', 'Planned'), ('InProgress', 'In Progress'), ('Deployed', 'Deployed'), ('RolledBack', 'Rolled Back'), ('Canceled', 'Canceled')], default='Draft', max_length=20)),
                ('risk', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('VeryHigh', 'Very High')], default='Normal', max_length=20)),
                ('risk_description', models.TextField(blank=True)),
                ('mitigation', models.TextField(blank=True)),
                ('rollback_plan', models.TextField(blank=True)),
                ('communication_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('solution_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Inbox', 'Inbox'), ('Backlog', 'Backlog'), ('Working', 'Working'), ('Testing', 'Testing'), ('ReadyForRelease', 'Ready for Release'), ('Closed', 'Closed')], default='Inbox', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to=settings.AUTH_USER_MODEL)),
                ('changes', models.ManyToManyField(blank=True, related_name='items', to='core.change')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.item')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_items', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.itemtype')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalIssueMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('number', models.IntegerField()),
                ('kind', models.CharField(choices=[('Issue', 'Issue'), ('PR', 'Pull Request')], max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('html_url', models.URLField()),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='core.item')),
            ],
            options={
                'ordering': ['item', 'kind', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ItemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Internal', 'Internal')], default='Public', max_length=20)),
                ('kind', models.CharField(choices=[('Note', 'Note'), ('Comment', 'Comment'), ('EmailIn', 'Email In'), ('EmailOut', 'Email Out')], default='Comment', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('external_from', models.EmailField(blank=True, max_length=254)),
                ('external_to', models.EmailField(blank=True, max_length=254)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('in_reply_to', models.CharField(blank=True, max_length=255)),
                ('delivery_status', models.CharField(choices=[('Draft', 'Draft'), ('Queued', 'Queued'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.item')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Project', 'Project'), ('View', 'View'), ('Entity', 'Entity'), ('Class', 'Class'), ('Action', 'Action'), ('Report', 'Report'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_nodes', to='core.node')),
            ],
            options={
                'ordering': ['project', 'type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='items', to='core.node'),
        ),
        migrations.AddField(
            model_name='item',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.organisation'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('github_owner', models.CharField(blank=True, max_length=255)),
                ('github_repo', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Working', 'Working'), ('Canceled', 'Canceled'), ('Finished', 'Finished')], default='New', max_length=20)),
                ('sentry_dsn', models.CharField(blank=True, max_length=500)),
                ('sentry_project_slug', models.CharField(blank=True, max_length=255)),
                ('sentry_auth_token', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('sentry_enable_auto_fetch', models.BooleanField(default=False)),
                ('clients', models.ManyToManyField(blank=True, related_name='projects', to='core.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.project'),
        ),
        migrations.AddField(
            model_name='item',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.project'),
        ),
        migrations.AddField(
            model_name='change',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.project'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('risk', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('VeryHigh', 'Very High')], default='Normal', max_length=20)),
                ('risk_description', models.TextField(blank=True)),
                ('risk_mitigation', models.TextField(blank=True)),
                ('rescue_measure', models.TextField(blank=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Working', 'Working'), ('Closed', 'Closed')], default='Planned', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='core.project')),
            ],
            options={
                'ordering': ['-update_date', 'project', 'name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='solution_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.release'),
        ),
        migrations.AddField(
            model_name='change',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='core.release'),
        ),
        migrations.CreateModel(
            name='AttachmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('ProjectFile', 'Project File'), ('ItemFile', 'Item File'), ('CommentAttachment', 'Comment Attachment')], max_length=30)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.attachment')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['attachment'],
                'constraints': [models.UniqueConstraint(fields=('attachment', 'target_content_type', 'target_object_id'), name='unique_attachment_target')],
            },
        ),
        migrations.CreateModel(
            name='ChangeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.change')),
            ],
            options={
                'ordering': ['change', 'approver'],
                'constraints': [models.UniqueConstraint(fields=('change', 'approver'), name='unique_change_approver')],
            },
        ),
        migrations.CreateModel(
            name='ItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('DependOn', 'Depends On'), ('Similar', 'Similar'), ('Related', 'Related')], max_length=20)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='core.item')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='core.item')),
            ],
            options={
                'ordering': ['from_item', 'to_item'],
                'indexes': [models.Index(fields=['from_item', 'to_item'], name='core_itemre_from_it_912e06_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_item', 'to_item', 'relation_type'), name='unique_item_relation')],
            },
        ),
        migrations.CreateModel(
            name='UserOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organisations', to='core.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organisation', 'user'],
                'constraints': [models.UniqueConstraint(fields=('user', 'organisation'), name='unique_user_organisation'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_organisation_per_user')],
            },
        ),
    ]
