# Generated by Django 5.2.10 on 2026-01-24 15:56

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('OpenAI', 'OpenAI'), ('Gemini', 'Gemini'), ('Claude', 'Claude')], max_length=20)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('organization_id', models.CharField(blank=True, help_text='Optional: For OpenAI organization', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['provider_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_id', models.CharField(help_text='Provider model string (e.g., gpt-4, gemini-pro)', max_length=255)),
                ('input_price_per_1m_tokens', models.DecimalField(blank=True, decimal_places=4, help_text='Price per 1M input tokens', max_digits=10, null=True)),
                ('output_price_per_1m_tokens', models.DecimalField(blank=True, decimal_places=4, help_text='Price per 1M output tokens', max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default model for this provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIJobsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(default='core.ai', help_text="Agent name or 'core.ai' for direct calls", max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Error', 'Error')], default='Pending', max_length=20)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('costs', models.DecimalField(blank=True, decimal_places=6, help_text='Total cost in USD', max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.aimodel')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Job History',
                'verbose_name_plural': 'AI Jobs History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_id'), name='unique_provider_model'),
        ),
        migrations.AddIndex(
            model_name='aijobshistory',
            index=models.Index(fields=['-timestamp'], name='core_aijobs_timesta_1f459d_idx'),
        ),
        migrations.AddIndex(
            model_name='aijobshistory',
            index=models.Index(fields=['provider', 'model'], name='core_aijobs_provide_cd69da_idx'),
        ),
        migrations.AddIndex(
            model_name='aijobshistory',
            index=models.Index(fields=['user'], name='core_aijobs_user_id_2a6ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='aijobshistory',
            index=models.Index(fields=['status'], name='core_aijobs_status_7be391_idx'),
        ),
    ]
