# Generated by Django 5.2.10 on 2026-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiprovider_aimodel_aijobshistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphapiconfiguration',
            name='default_mail_sender',
            field=models.EmailField(blank=True, help_text='Default sender email (UPN) for outbound emails, e.g., support@domain.tld', max_length=254),
        ),
    ]
