# Generated by Django 5.2.10 on 2026-01-24 16:40

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_graph_default_mail_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconfiguration',
            name='default_github_owner',
            field=models.CharField(blank=True, help_text='Default GitHub owner/organization', max_length=255),
        ),
        migrations.AddField(
            model_name='githubconfiguration',
            name='enable_github',
            field=models.BooleanField(default=False, help_text='Enable GitHub integration'),
        ),
        migrations.AddField(
            model_name='githubconfiguration',
            name='github_api_base_url',
            field=models.URLField(default='https://api.github.com', help_text='GitHub API base URL'),
        ),
        migrations.AddField(
            model_name='githubconfiguration',
            name='github_copilot_username',
            field=models.CharField(blank=True, help_text='GitHub username for Copilot attribution', max_length=255),
        ),
        migrations.AddField(
            model_name='githubconfiguration',
            name='github_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='GitHub Personal Access Token or App token'),
        ),
    ]
