# Generated by Django 5.2.10 on 2026-01-24 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_github_configuration_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='attachmentlink',
            name='unique_attachment_target',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='size',
            new_name='size_bytes',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='attachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='storage_path',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachmentlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['created_at'], name='core_attach_created_d54bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['sha256'], name='core_attach_sha256_53692d_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.UniqueConstraint(fields=('attachment', 'target_content_type', 'target_object_id', 'role'), name='unique_attachment_target_role'),
        ),
    ]
