# Generated by Django 5.2.10 on 2026-01-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_attachment_storage_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganisation',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Approver', 'Approver'), ('ISB', 'ISB'), ('Managemenet', 'Management')], default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Approver', 'Approver'), ('ISB', 'ISB'), ('Managemenet', 'Management')], default='User', max_length=20),
        ),
    ]
