# Generated by Django 5.2.10 on 2026-01-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userorganisation_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaviateconfiguration',
            name='grpc_port',
            field=models.IntegerField(default=50051, help_text='gRPC port for Weaviate (default: 50051)'),
        ),
        migrations.AddField(
            model_name='weaviateconfiguration',
            name='http_port',
            field=models.IntegerField(default=8080, help_text='HTTP port for Weaviate (default: 8080, local install often uses 8081)'),
        ),
        migrations.AlterField(
            model_name='weaviateconfiguration',
            name='url',
            field=models.URLField(blank=True, help_text='Weaviate instance URL (e.g., http://localhost or http://192.168.1.100)'),
        ),
    ]
