# Generated by Django 5.2.10 on 2026-01-25 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_weaviate_port_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaviateconfiguration',
            name='grpc_port',
            field=models.IntegerField(default=50051, help_text='gRPC port for Weaviate (default: 50051)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='weaviateconfiguration',
            name='http_port',
            field=models.IntegerField(default=8080, help_text='HTTP port for Weaviate (default: 8080, local install often uses 8081)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
