# Generated by Django 5.2.10 on 2026-01-25 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_port_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='github_last_synced',
            field=models.DateTimeField(blank=True, help_text='Last sync time from GitHub', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='github_repo_path',
            field=models.CharField(blank=True, help_text='Path in GitHub repository (e.g., docs/README.md)', max_length=1000),
        ),
        migrations.AddField(
            model_name='attachment',
            name='github_sha',
            field=models.CharField(blank=True, help_text='GitHub blob SHA for version tracking', max_length=40),
        ),
        migrations.AlterField(
            model_name='weaviateconfiguration',
            name='http_port',
            field=models.IntegerField(default=8081, help_text='HTTP port for Weaviate (default: 8080, local install often uses 8081)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['github_repo_path'], name='core_attach_github__1fdd03_idx'),
        ),
    ]
