# Generated by Django 5.2.10 on 2026-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_ai_generated_comment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='is_safety_relevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='change',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='changes', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='changeapproval',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether the approval has been granted'),
        ),
        migrations.AddField(
            model_name='changeapproval',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the approval was granted', null=True),
        ),
        migrations.AddField(
            model_name='changeapproval',
            name='informed_at',
            field=models.DateTimeField(blank=True, help_text='When the approver was informed about the change', null=True),
        ),
        migrations.AddField(
            model_name='changeapproval',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the approval process'),
        ),
        migrations.AlterField(
            model_name='attachmentlink',
            name='role',
            field=models.CharField(choices=[('ProjectFile', 'Project File'), ('ItemFile', 'Item File'), ('CommentAttachment', 'Comment Attachment'), ('ApproverAttachment', 'Approver Attachment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Inbox', '📥 Inbox'), ('Backlog', '📋 Backlog'), ('Working', '🚧 Working'), ('Testing', '🧪 Testing'), ('ReadyForRelease', '✅ Ready for Release'), ('Planing', '📅 Planing'), ('Specification', '📝 Specification'), ('Closed', '✔ Closed')], default='Inbox', max_length=20),
        ),
    ]
