# Generated by Django 5.2.10 on 2026-01-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_extend_change_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='type',
            field=models.CharField(blank=True, choices=[('Major', 'Major'), ('Minor', 'Minor'), ('Hotfix', 'Hotfix'), ('Securityfix', 'Securityfix')], max_length=20, null=True),
        ),
    ]
