# Generated by Django 5.2.10 on 2026-01-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_release_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Technical identifier for the template (e.g., issue-created-confirmation)', max_length=100, unique=True)),
                ('subject', models.CharField(help_text='Email subject line. Placeholders are allowed but not evaluated.', max_length=500)),
                ('message', models.TextField(help_text='Email content (Markdown or HTML). Placeholders are allowed but not evaluated.')),
                ('from_name', models.CharField(blank=True, help_text='Optional sender name', max_length=255)),
                ('from_address', models.EmailField(blank=True, help_text='Optional sender email address', max_length=254)),
                ('cc_address', models.EmailField(blank=True, help_text='Optional CC email address', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mail Template',
                'verbose_name_plural': 'Mail Templates',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['is_active'], name='core_mailte_is_acti_568372_idx')],
            },
        ),
    ]
