# Generated by Django 5.2.10 on 2026-01-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailActionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is active and can be used')),
                ('item_status', models.CharField(choices=[('Inbox', '📥 Inbox'), ('Backlog', '📋 Backlog'), ('Working', '🚧 Working'), ('Testing', '🧪 Testing'), ('ReadyForRelease', '✅ Ready for Release'), ('Planing', '📅 Planing'), ('Specification', '📝 Specification'), ('Closed', '✔ Closed')], help_text='Issue status for which this mapping applies', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.ForeignKey(help_text='Issue type for which this mapping applies', on_delete=django.db.models.deletion.CASCADE, related_name='mail_action_mappings', to='core.itemtype')),
                ('mail_template', models.ForeignKey(help_text='Mail template to use for this status/type combination', on_delete=django.db.models.deletion.PROTECT, related_name='mail_action_mappings', to='core.mailtemplate')),
            ],
            options={
                'verbose_name': 'Mail Action Mapping',
                'verbose_name_plural': 'Mail Action Mappings',
                'ordering': ['item_status', 'item_type'],
                'indexes': [models.Index(fields=['is_active'], name='core_mailac_is_acti_c566e1_idx'), models.Index(fields=['item_status', 'item_type'], name='core_mailac_item_st_2c0912_idx')],
            },
        ),
    ]
