# Generated by Django 5.2.10 on 2026-01-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_mailactionmapping_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='message',
            field=models.TextField(help_text='Email content (Markdown or HTML). Use {{ issue.variable }} placeholders (e.g., {{ issue.organisation }}, {{ issue.solution_release }}).'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(help_text='Email subject line. Use {{ issue.variable }} placeholders (e.g., {{ issue.title }}, {{ issue.description }}).', max_length=500),
        ),
    ]
