# Generated by Django 5.2.10 on 2026-01-29 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_mailtemplate_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_followers', to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['item'], name='core_itemfo_item_id_e688e3_idx'), models.Index(fields=['user'], name='core_itemfo_user_id_fd38d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'user'), name='unique_item_follower')],
            },
        ),
    ]
