# Generated by Django 5.2.10 on 2026-01-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_item_follower_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='mail_domains',
            field=models.TextField(blank=True, help_text='Mail domains for this organization, one per line (e.g., example.com)'),
        ),
    ]
