# Generated by Django 5.2.10 on 2026-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_mail_domains_to_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='azure_ad_object_id',
            field=models.CharField(blank=True, help_text='Azure AD Object ID for SSO', max_length=255, null=True, unique=True),
        ),
    ]
