# Generated by Django 5.2.10 on 2026-01-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_moved_mail_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomment',
            name='body_original_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemcomment',
            name='external_cc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcomment',
            name='external_to',
            field=models.TextField(blank=True),
        ),
    ]
