# Generated by Django 5.2.10 on 2026-01-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_moved_mail_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_input',
            field=models.TextField(blank=True, help_text='Original email text, not modified by AI'),
        ),
    ]
