# Generated by Django 5.2.10 on 2026-01-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_email_reply_fields'),
        ('core', '0020_add_user_input_field'),
    ]

    operations = [
    ]
