# Generated by Django 5.2.10 on 2026-01-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20260130_0832'),
        ('core', '0021_merge_20260130_0837'),
        ('core', '0021_merge_20260130_0839'),
    ]

    operations = [
    ]
