# Generated by Django 5.2.10 on 2026-01-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20260130_0902'),
        ('core', '0022_merge_20260130_0907'),
    ]

    operations = [
    ]
