# Generated by Django 5.2.10 on 2026-01-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20260130_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='message',
            field=models.TextField(help_text='Email content (Markdown or HTML). Use {{ issue.variable }} placeholders (e.g., {{ issue.organisation }}, {{ issue.solution_release }}, {{ issue.solution_description }}).'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(help_text='Email subject line. Use {{ issue.variable }} placeholders (e.g., {{ issue.title }}, {{ issue.description }}, {{ issue.solution_description }}).', max_length=500),
        ),
        migrations.CreateModel(
            name='OrganisationEmbedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this embed access is currently enabled')),
                ('embed_token', models.CharField(help_text='Cryptographically secure token for embed access', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(help_text='Organisation that has embed access', on_delete=django.db.models.deletion.CASCADE, related_name='embed_projects', to='core.organisation')),
                ('project', models.ForeignKey(help_text='Project that can be embedded', on_delete=django.db.models.deletion.CASCADE, related_name='embed_accesses', to='core.project')),
            ],
            options={
                'verbose_name': 'Organisation Embed Project',
                'verbose_name_plural': 'Organisation Embed Projects',
                'ordering': ['organisation', 'project'],
                'indexes': [models.Index(fields=['embed_token'], name='core_organi_embed_t_66f958_idx'), models.Index(fields=['is_enabled'], name='core_organi_is_enab_60b8a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'project'), name='unique_organisation_project_embed')],
            },
        ),
    ]
