# Generated by Django 5.2.10 on 2026-01-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20260130_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='message',
            field=models.TextField(help_text='Email content (Markdown or HTML). Use {{ issue.variable }} placeholders (e.g., {{ issue.organisation }}, {{ issue.solution_release }}, {{ issue.solution_description }}).'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(help_text='Email subject line. Use {{ issue.variable }} placeholders (e.g., {{ issue.title }}, {{ issue.description }}, {{ issue.solution_description }}).', max_length=500),
        ),
    ]
