# Generated by Django 5.2.10 on 2026-01-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_organisation_embed_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationembedproject',
            options={'ordering': ['organisation_id', 'project_id'], 'verbose_name': 'Organisation Embed Project', 'verbose_name_plural': 'Organisation Embed Projects'},
        ),
        migrations.AddField(
            model_name='itemtype',
            name='description',
            field=models.TextField(blank=True, help_text='Description shown to customers when creating issues in the embed portal'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='message',
            field=models.TextField(help_text='Email content (Markdown or HTML). Use {{ issue.variable }} placeholders (e.g., {{ issue.organisation }}, {{ issue.solution_release }}, {{ issue.solution_description }}). Note: {{ solution_description }} without prefix also works for backward compatibility.'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(help_text='Email subject line. Use {{ issue.variable }} placeholders (e.g., {{ issue.title }}, {{ issue.description }}, {{ issue.solution_description }}). Note: {{ solution_description }} without prefix also works for backward compatibility.', max_length=500),
        ),
    ]
