# Generated by Django 5.2.10 on 2026-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_mailtemplate_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='message',
            field=models.TextField(help_text='Email content (Markdown or HTML). Use {{ issue.variable }} placeholders (e.g., {{ issue.organisation }}, {{ issue.solution_release }}, {{ issue.solution_description }}). Note: {{ solution_description }} without prefix also works for backward compatibility.'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(help_text='Email subject line. Use {{ issue.variable }} placeholders (e.g., {{ issue.title }}, {{ issue.description }}, {{ issue.solution_description }}). Note: {{ solution_description }} without prefix also works for backward compatibility.', max_length=500),
        ),
    ]
