# Generated by Django 5.2.10 on 2026-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_itemtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content_id',
            field=models.CharField(blank=True, help_text="Content-ID for inline email attachments (e.g., 'image001.png@01D9...')", max_length=500),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_id'], name='core_attach_content_2f0b83_idx'),
        ),
    ]
