# Generated by Django 5.2.10 on 2026-01-31 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_attachment_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='message',
            field=models.TextField(help_text='Email content (Markdown or HTML). Use {{ issue.variable }} placeholders (e.g., {{ issue.requester }}, {{ issue.requester_first_name }}, {{ issue.organisation }}, {{ issue.solution_release }}, {{ issue.solution_description }}). Note: {{ solution_description }} without prefix also works for backward compatibility.'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(help_text='Email subject line. Use {{ issue.variable }} placeholders (e.g., {{ issue.title }}, {{ issue.requester }}, {{ issue.requester_first_name }}, {{ issue.description }}, {{ issue.solution_description }}). Note: {{ solution_description }} without prefix also works for backward compatibility.', max_length=500),
        ),
        migrations.CreateModel(
            name='ReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(help_text="Report type identifier (e.g., 'change.v1')", max_length=100)),
                ('object_type', models.CharField(help_text="Type of object this report is for (e.g., 'change')", max_length=100)),
                ('object_id', models.CharField(help_text='ID of the object', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_json', models.TextField(help_text='Snapshot of the data used to generate this report')),
                ('pdf_file', models.FileField(upload_to='reports/%Y/%m/%d/')),
                ('sha256', models.CharField(help_text='SHA256 hash of the PDF for integrity verification', max_length=64)),
                ('metadata_json', models.TextField(blank=True, help_text='Additional metadata (template version, etc.)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_key', 'object_type', 'object_id'], name='core_report_report__9285b7_idx'), models.Index(fields=['created_at'], name='core_report_created_869a53_idx')],
            },
        ),
    ]
