# Generated by Django 5.2.10 on 2026-01-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_organisation_embed_project'),
        ('core', '0025_alter_mailtemplate_message_and_more'),
    ]

    operations = [
    ]
