# Generated by Django 5.2.10 on 2026-01-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_mailtemplate_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdocument',
            name='metadata_json',
            field=models.TextField(blank=True, help_text='Additional metadata (template version, etc.)', null=True),
        ),
    ]
