# Generated by Django 5.2.10 on 2026-01-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20260130_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationembedproject',
            options={'ordering': ['organisation_id', 'project_id'], 'verbose_name': 'Organisation Embed Project', 'verbose_name_plural': 'Organisation Embed Projects'},
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='message',
            field=models.TextField(help_text='Email content (Markdown or HTML). Use {{ issue.variable }} placeholders (e.g., {{ issue.organisation }}, {{ issue.solution_release }}, {{ issue.solution_description }}). Note: {{ solution_description }} without prefix also works for backward compatibility.'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(help_text='Email subject line. Use {{ issue.variable }} placeholders (e.g., {{ issue.title }}, {{ issue.description }}, {{ issue.solution_description }}). Note: {{ solution_description }} without prefix also works for backward compatibility.', max_length=500),
        ),
    ]
