# Generated by Django 5.2.10 on 2026-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_reportdocument_metadata_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='intern',
            field=models.BooleanField(default=False),
        ),
    ]
