# Generated by Django 5.2.10 on 2026-01-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_itemtype_description'),
        ('core', '0027_alter_organisationembedproject_options_and_more'),
    ]

    operations = [
    ]
