# Generated by Django 5.2.10 on 2026-01-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_attachment_content_id'),
        ('core', '0028_merge_20260130_2101'),
    ]

    operations = [
    ]
