# Generated by Django 5.2.10 on 2026-01-31 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_reportdocument_metadata_json'),
        ('core', '0030_alter_mailtemplate_message_and_more'),
    ]

    operations = [
    ]
