# Generated by Django 5.2.10 on 2026-02-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_item_intern_field'),
        ('core', '0031_merge_20260131_2355'),
    ]

    operations = [
    ]
