# Generated by Django 5.2.10 on 2026-02-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20260201_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-planned_date', '-updated_at', 'project', 'name']},
        ),
        migrations.AddField(
            model_name='change',
            name='planned_date',
            field=models.DateField(blank=True, help_text='Planned change date (date only)', null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='planned_date',
            field=models.DateField(blank=True, help_text='Planned release date', null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
