# Generated by Django 5.2.10 on 2026-02-01 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_planned_date_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueStandardAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Unique key for this standard answer', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Short label shown in UI', max_length=200)),
                ('text', models.TextField(help_text='Full answer text')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this answer is available for selection')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='IssueOpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question text')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Answered', 'Answered'), ('Dismissed', 'Dismissed')], default='Open', help_text='Current status of the question', max_length=20)),
                ('answer_text', models.TextField(blank=True, help_text='Free text answer if provided', null=True)),
                ('answer_type', models.CharField(choices=[('FreeText', 'Free Text'), ('StandardAnswer', 'Standard Answer'), ('None', 'None')], default='None', help_text='Type of answer provided', max_length=20)),
                ('standard_answer_key', models.SlugField(blank=True, help_text='Key of standard answer if used', max_length=100, null=True)),
                ('source', models.CharField(choices=[('AIAgent', 'AI Agent'), ('Human', 'Human')], default='AIAgent', help_text='Source of this question', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_at', models.DateTimeField(blank=True, help_text='When the question was answered or dismissed', null=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order within the issue (lower numbers first)')),
                ('answered_by', models.ForeignKey(blank=True, help_text='User who answered or dismissed the question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='core.item')),
                ('standard_answer', models.ForeignKey(blank=True, help_text='Standard answer if selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_uses', to='core.issuestandardanswer')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['issue', 'status'], name='core_issueo_issue_i_bd89a4_idx'), models.Index(fields=['created_at'], name='core_issueo_created_c806ee_idx')],
            },
        ),
    ]
