# Generated by Django 5.2.10 on 2026-02-01 21:55

from django.db import migrations


def add_initial_standard_answers(apps, schema_editor):
    """Add initial standard answers for open questions."""
    IssueStandardAnswer = apps.get_model('core', 'IssueStandardAnswer')
    
    initial_answers = [
        {
            'key': 'project_context',
            'label': 'Ergibt sich aus dem Projektkontext',
            'text': 'Ergibt sich aus dem Projektkontext',
            'sort_order': 10,
        },
        {
            'key': 'copilot_decides',
            'label': 'Copilot kann das selbst entscheiden',
            'text': 'Copilot kann das selbst entscheiden',
            'sort_order': 20,
        },
        {
            'key': 'default_behavior',
            'label': 'Standardverhalten der Anwendung',
            'text': 'Standardverhalten der Anwendung',
            'sort_order': 30,
        },
        {
            'key': 'not_relevant',
            'label': 'Nicht relevant / ignorieren',
            'text': 'Nicht relevant / ignorieren',
            'sort_order': 40,
        },
    ]
    
    for answer_data in initial_answers:
        IssueStandardAnswer.objects.get_or_create(
            key=answer_data['key'],
            defaults=answer_data
        )


def remove_initial_standard_answers(apps, schema_editor):
    """Remove initial standard answers."""
    IssueStandardAnswer = apps.get_model('core', 'IssueStandardAnswer')
    
    keys = ['project_context', 'copilot_decides', 'default_behavior', 'not_relevant']
    IssueStandardAnswer.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_open_questions_models'),
    ]

    operations = [
        migrations.RunPython(add_initial_standard_answers, remove_initial_standard_answers),
    ]
