# Generated by Django 5.2.10 on 2026-02-02 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_initial_standard_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when release was closed', null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='User who closed the release', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_releases', to=settings.AUTH_USER_MODEL),
        ),
    ]
