# Generated by Django 5.2.10 on 2026-02-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_release_closed_at_release_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationembedproject',
            name='allowed_origins',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of allowed origins for iframe embedding (e.g., https://app.example.com, https://portal.example.org)'),
        ),
    ]
