# Generated by Django 5.2.11 on 2026-02-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_allowed_origins_to_embed_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Your Company Name', help_text='Company name', max_length=255)),
                ('email', models.EmailField(default='company@example.com', help_text='Company contact email address', max_length=254)),
                ('address', models.TextField(default='Street Address\nZIP City\nCountry', help_text='Company address (Street, ZIP, City, Country)')),
                ('base_url', models.URLField(default='https://example.com', help_text='Base URL of the application', max_length=500)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (PNG, JPG, WEBP, GIF - max 5 MB)', null=True, upload_to='global_settings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Approver', 'Approver'), ('ISB', 'ISB'), ('Managemenet', 'Management'), ('Info', 'Info'), ('Development', 'Development')], default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='userorganisation',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Approver', 'Approver'), ('ISB', 'ISB'), ('Managemenet', 'Management'), ('Info', 'Info'), ('Development', 'Development')], default='User', max_length=20),
        ),
    ]
