# Generated by Django 5.2.11 on 2026-02-03 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_allowed_origins_to_embed_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.CharField(blank=True, choices=[('Major', 'Major'), ('Minor', 'Minor'), ('Bugfix', 'Bugfix'), ('Hotfix', 'Hotfix'), ('Securityfix', 'Securityfix')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Approver', 'Approver'), ('ISB', 'ISB'), ('Managemenet', 'Management'), ('Info', 'Info'), ('Development', 'Development')], default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='userorganisation',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Approver', 'Approver'), ('ISB', 'ISB'), ('Managemenet', 'Management'), ('Info', 'Info'), ('Development', 'Development')], default='User', max_length=20),
        ),
        migrations.CreateModel(
            name='ChangePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('VeryHigh', 'Very High')], max_length=20)),
                ('security_relevant', models.BooleanField(default=False)),
                ('release_type', models.CharField(blank=True, choices=[('Major', 'Major'), ('Minor', 'Minor'), ('Bugfix', 'Bugfix'), ('Hotfix', 'Hotfix'), ('Securityfix', 'Securityfix')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['risk_level', 'security_relevant', 'release_type'],
                'constraints': [models.UniqueConstraint(fields=('risk_level', 'security_relevant', 'release_type'), name='unique_change_policy')],
            },
        ),
        migrations.CreateModel(
            name='ChangePolicyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Approver', 'Approver'), ('ISB', 'ISB'), ('Managemenet', 'Management'), ('Info', 'Info'), ('Development', 'Development')], max_length=20)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_roles', to='core.changepolicy')),
            ],
            options={
                'ordering': ['policy', 'role'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'role'), name='unique_policy_role')],
            },
        ),
    ]
