# Generated by Django 5.2.10 on 2026-02-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_change_policy_models'),
        ('core', '0038_globalsettings_alter_user_role_and_more'),
    ]

    operations = [
    ]
