# Generated by Django 5.2.11 on 2026-02-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20260204_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='short',
            field=models.CharField(blank=True, help_text='Short code/abbreviation for this organization (max 10 characters)', max_length=10),
        ),
    ]
