# Generated by Django 5.2.11 on 2026-02-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20260203_2216'),
        ('core', '0040_add_short_field_to_organisation'),
    ]

    operations = [
    ]
