# Generated by Django 5.2.10 on 2026-02-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20260204_0955'),
        ('core', '0041_merge_20260204_1208'),
    ]

    operations = [
    ]
