# Generated by Django 5.2.11 on 2026-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20260204_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, db_index=True, help_text='File type determined from extension (e.g., PDF, DOCX, MD)', max_length=20),
        ),
    ]
