# Generated by Django 5.2.10 on 2026-02-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_file_type_to_attachment'),
        ('core', '0042_merge_20260204_1638'),
    ]

    operations = [
    ]
