# Generated by Django 5.2.11 on 2026-02-06 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20260204_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBlueprintCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Issue Blueprint Category',
                'verbose_name_plural': 'Issue Blueprint Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssueBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description_md', models.TextField(help_text='Description in Markdown format. Acceptance criteria should be included here.')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, help_text='List of tags as strings', null=True)),
                ('default_labels', models.JSONField(blank=True, help_text='List of default labels as strings', null=True)),
                ('default_risk_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('VeryHigh', 'Very High')], help_text='Default risk level for issues created from this blueprint', max_length=20, null=True)),
                ('default_security_relevant', models.BooleanField(blank=True, help_text='Default security relevance for issues created from this blueprint', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this blueprint')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this blueprint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blueprints', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprints', to='core.issueblueprintcategory')),
            ],
            options={
                'verbose_name': 'Issue Blueprint',
                'verbose_name_plural': 'Issue Blueprints',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['title', 'category', 'version'], name='core_issueb_title_ac5d71_idx'), models.Index(fields=['is_active'], name='core_issueb_is_acti_612e91_idx')],
            },
        ),
    ]
