# Generated by Django 5.2.11 on 2026-02-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_issueblueprintcategory_issueblueprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueblueprint',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes about this blueprint'),
        ),
    ]
