# Generated by Django 5.2.11 on 2026-02-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_issueblueprint_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='target_object_id',
            field=models.CharField(max_length=255),
        ),
    ]
