# Generated by Django 5.2.11 on 2026-02-10 20:57

from django.db import migrations, models


def create_default_system_setting(apps, schema_editor):
    """Create the default SystemSetting instance with specified default values."""
    SystemSetting = apps.get_model('core', 'SystemSetting')
    if not SystemSetting.objects.exists():
        SystemSetting.objects.create(
            id=1,
            system_name='Agira Issue Tracking v1.0',
            company='Agira Software Enterprises',
            email='agira@angermeier.net'
        )


def reverse_create_default_system_setting(apps, schema_editor):
    """Remove the default SystemSetting instance."""
    SystemSetting = apps.get_model('core', 'SystemSetting')
    SystemSetting.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_planing_specification_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Agira Issue Tracking v1.0', help_text='System name', max_length=255)),
                ('company', models.CharField(default='Agira Software Enterprises', help_text='Company name', max_length=255)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo (PNG, JPG, WEBP, GIF - max 5 MB). Stored as relative path.', null=True, upload_to='system_settings/')),
                ('email', models.EmailField(default='agira@angermeier.net', help_text='Company contact email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.RunPython(create_default_system_setting, reverse_create_default_system_setting),
    ]
