# Generated by Django 5.2.11 on 2026-02-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_update_changeapproval_status_and_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(),
        ),
    ]
