# Generated by Django 5.2.11 on 2026-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_title_length_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentlink',
            name='role',
            field=models.CharField(choices=[('ProjectFile', 'Project File'), ('ItemFile', 'Item File'), ('CommentAttachment', 'Comment Attachment'), ('ApproverAttachment', 'Approver Attachment'), ('transkript', 'Meeting Transcript')], max_length=30),
        ),
    ]
