# Generated by Django 5.2.11 on 2026-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_attachmentlink_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.TextField(blank=True, help_text='ISO-compliant short description (max 3-4 sentences)'),
        ),
    ]
