# Generated by Django 5.2.11 on 2026-02-19 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_short_description_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
