# Generated by Django 5.2.10 on 2026-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_responsible_mail_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Abstained', 'Abstained'), ('Info', 'Info')], default='Pending', max_length=20),
        ),
    ]
