# Generated by Django 5.2.11 on 2026-02-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_responsible_mail_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeapproval',
            name='decision_token',
            field=models.CharField(blank=True, help_text='Token for email-based approve/reject decision', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='changeapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Abstained', 'Abstained'), ('Info', 'Info')], default='Pending', max_length=20),
        ),
    ]
