# Generated by Django 5.2.11 on 2026-02-19 11:31

from django.db import migrations, models
import secrets


def populate_decision_tokens(apps, schema_editor):
    """Populate decision_token for existing ChangeApproval records."""
    ChangeApproval = apps.get_model('core', 'ChangeApproval')
    
    # Get all ChangeApproval records that don't have a decision_token
    approvals_without_token = ChangeApproval.objects.filter(decision_token='')
    
    # Get existing tokens to avoid collisions
    existing_tokens = set(ChangeApproval.objects.exclude(decision_token='').values_list('decision_token', flat=True))
    
    # Generate unique tokens for each approval
    approvals_to_update = []
    
    for approval in approvals_without_token.iterator():
        # Generate a unique token (retry if collision detected)
        token = secrets.token_urlsafe(32)
        while token in existing_tokens:
            token = secrets.token_urlsafe(32)
        
        existing_tokens.add(token)
        approval.decision_token = token
        approvals_to_update.append(approval)
    
    # Bulk update all records in a single query
    if approvals_to_update:
        ChangeApproval.objects.bulk_update(approvals_to_update, ['decision_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_responsible_mail_template'),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='changeapproval',
            name='decision_token',
            field=models.CharField(blank=True, help_text='Token for email-based approve/reject decision', max_length=64),
        ),
        # Step 2: Populate existing records with unique tokens
        migrations.RunPython(
            populate_decision_tokens,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 3: Add unique constraint after data is populated
        migrations.AlterField(
            model_name='changeapproval',
            name='decision_token',
            field=models.CharField(blank=True, help_text='Token for email-based approve/reject decision', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='changeapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Abstained', 'Abstained'), ('Info', 'Info')], default='Pending', max_length=20),
        ),
    ]
