# Generated by Django 5.2.11 on 2026-02-19 11:34

from django.db import migrations


def create_change_approval_mail_template(apps, schema_editor):
    """Create the change-approval-request MailTemplate."""
    MailTemplate = apps.get_model('core', 'MailTemplate')
    
    # Check if template already exists
    if MailTemplate.objects.filter(key='change-approval-request').exists():
        return
    
    # Create the template
    MailTemplate.objects.create(
        key='change-approval-request',
        subject='Change Approval benötigt: {{ change_title }} ({{ change_id }})',
        message='''<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background-color: #007bff; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; background-color: #f8f9fa; }
        .button { display: inline-block; padding: 12px 24px; margin: 10px 5px; text-decoration: none; border-radius: 4px; font-weight: bold; }
        .btn-approve { background-color: #28a745; color: white; }
        .btn-reject { background-color: #dc3545; color: white; }
        .footer { padding: 20px; text-align: center; color: #6c757d; font-size: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>Change Approval Request</h2>
        </div>
        <div class="content">
            <p>Hello,</p>
            <p>Your approval is requested for the following change:</p>
            <p><strong>Change ID:</strong> {{ change_id }}</p>
            <p><strong>Title:</strong> {{ change_title }}</p>
            <p>Please review the attached Change PDF and provide your decision by clicking one of the buttons below:</p>
            <div style="text-align: center; margin: 30px 0;">
                <a href="{{ approve_url }}" class="button btn-approve">✅ Approve</a>
                <a href="{{ reject_url }}" class="button btn-reject">❌ Reject</a>
            </div>
            <p><strong>Note:</strong> These links are unique to you and should not be shared.</p>
        </div>
        <div class="footer">
            <p>This is an automated message from Agira Change Management System.</p>
        </div>
    </div>
</body>
</html>''',
        is_active=True,
    )


def remove_change_approval_mail_template(apps, schema_editor):
    """Remove the change-approval-request MailTemplate."""
    MailTemplate = apps.get_model('core', 'MailTemplate')
    MailTemplate.objects.filter(key='change-approval-request').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_add_changeapproval_decision_token'),
    ]

    operations = [
        migrations.RunPython(
            create_change_approval_mail_template,
            reverse_code=remove_change_approval_mail_template,
        ),
    ]

