# Generated by Django 5.2.10 on 2026-02-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_changeapproval_status'),
        ('core', '0056_add_change_approval_mail_template'),
    ]

    operations = [
    ]
