# Generated by Django 5.2.11 on 2026-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_add_change_approval_mail_template'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='changeapproval',
            name='unique_change_approver',
        ),
        migrations.AddField(
            model_name='changeapproval',
            name='role',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Agent', 'Agent'), ('Approver', 'Approver'), ('ISB', 'ISB'), ('Managemenet', 'Management'), ('Info', 'Info'), ('Development', 'Development')], help_text='The role for which this approver is assigned', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='changeapproval',
            constraint=models.UniqueConstraint(fields=('change', 'approver', 'role'), name='unique_change_approver_role'),
        ),
    ]
