# Generated by Django 5.2.10 on 2026-02-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_add_role_to_changeapproval'),
        ('core', '0057_merge_20260219_1302'),
    ]

    operations = [
    ]
