# Generated by Django 5.2.11 on 2026-03-01 15:27

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_add_change_update_mail_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_pat',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Personal GitHub token for creating issues'),
        ),
    ]
