# Generated by Django 5.2.15 on 2026-07-03 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_add_user_mcp_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeQueueJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('model', models.CharField(choices=[('sonnet', 'Sonnet'), ('opus', 'Opus')], default='sonnet', max_length=20)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pr_number', models.IntegerField(blank=True, null=True)),
                ('pr_url', models.URLField(blank=True, max_length=500, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('num_turns', models.IntegerField(blank=True, null=True)),
                ('total_cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('progress_text', models.TextField(blank=True, help_text='Current step, advanced by the worker — basis for the live view')),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claude_queue_jobs', to='core.item')),
                ('project', models.ForeignKey(help_text='Redundant with item.project for a fast per-project concurrency filter', on_delete=django.db.models.deletion.CASCADE, related_name='claude_queue_jobs', to='core.project')),
            ],
            options={
                'verbose_name': 'Claude Queue Job',
                'verbose_name_plural': 'Claude Queue Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='core_claude_project_4aae27_idx'), models.Index(fields=['status', 'created_at'], name='core_claude_status_14902b_idx')],
            },
        ),
    ]
