# Generated by Django 5.2.15 on 2026-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_claudequeuejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='claudequeuejob',
            name='worker_host',
            field=models.CharField(blank=True, help_text='Hostname of the worker that claimed this job', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claudequeuejob',
            name='worker_pid',
            field=models.IntegerField(blank=True, help_text='PID of the worker process that claimed this job', null=True),
        ),
    ]
