# Generated by Django 5.2.15 on 2026-07-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_claudequeuejob_worker_host_claudequeuejob_worker_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='suggested_model',
            field=models.CharField(choices=[('sonnet', 'Sonnet'), ('opus', 'Opus')], default='sonnet', help_text='AI-suggested Claude model for automated processing. A suggestion, not a gate — overridable in the UI.', max_length=20),
        ),
    ]
