# Generated by Django 5.2.14 on 2026-07-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_item_suggested_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='claudequeuejob',
            name='pr_state',
            field=models.CharField(blank=True, help_text='Latest known GitHub PR state: open, closed, or merged', max_length=50),
        ),
    ]
