# Generated by Django 5.2.14 on 2026-07-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_externalissuemapping_merge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pr_description',
            field=models.TextField(blank=True, help_text='Final pull request description, captured from GitHub on merge'),
        ),
    ]
