# Generated by Django 5.2.14 on 2026-07-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_item_pr_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='claudequeuejob',
            name='completion_uncertain',
            field=models.BooleanField(default=False, help_text='Job reached "done" but its outcome looks incomplete — needs a human look'),
        ),
        migrations.AddField(
            model_name='claudequeuejob',
            name='completion_uncertain_reason',
            field=models.TextField(blank=True, help_text='Short reason the job was flagged as completion_uncertain'),
        ),
    ]
