# Generated by Django 5.2.15 on 2026-07-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_claudequeuejob_completion_uncertain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Inbox', '📥 Inbox'), ('Backlog', '📋 Backlog'), ('Working', '🚧 Working'), ('Testing', '🧪 Testing'), ('Review', '👀 Review'), ('ReadyForRelease', '✅ Ready for Release'), ('Closed', '✔ Closed')], default='Inbox', max_length=20),
        ),
        migrations.AlterField(
            model_name='mailactionmapping',
            name='item_status',
            field=models.CharField(choices=[('Inbox', '📥 Inbox'), ('Backlog', '📋 Backlog'), ('Working', '🚧 Working'), ('Testing', '🧪 Testing'), ('ReadyForRelease', '✅ Ready for Release'), ('Closed', '✔ Closed')], help_text='Issue status for which this mapping applies (Review is not eligible for mail triggers)', max_length=20),
        ),
    ]
