# Generated by Django 5.2.15 on 2026-07-21 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_add_review_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, help_text="Users mentioned via @mention in this comment's body", related_name='comment_mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
