# Generated by Django 5.2.15 on 2026-08-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_add_comment_mention_mail_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='claudequeuejob',
            name='allow_api_key_fallback',
            field=models.BooleanField(default=False, help_text='If the subscription limit is hit, finish this job on the API key instead of waiting'),
        ),
        migrations.AddField(
            model_name='claudequeuejob',
            name='auth_mode',
            field=models.CharField(choices=[('oauth', 'Max/Pro subscription (OAuth)'), ('api_key', 'Anthropic API key')], default='oauth', help_text='How the latest run authenticated (subscription OAuth vs. API key)', max_length=20),
        ),
        migrations.AddField(
            model_name='claudequeuejob',
            name='limit_reset_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription quota is expected to reset; a waiting job is re-claimed after this time', null=True),
        ),
        migrations.AlterField(
            model_name='claudequeuejob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_limit', 'Waiting for quota'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
    ]
