# Generated by Django 5.2.15 on 2026-08-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_split_suggested_model_opus_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='epic_order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the parent epic. Sub-issues are worked strictly ascending; ties break by item id.'),
        ),
    ]
