# Generated by Django 5.2.15 on 2026-08-09 07:20

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_item_epic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='claudequeuejob',
            name='auth_credential_source',
            field=models.CharField(blank=True, choices=[('user', 'Personal credential of the job user'), ('shared', 'Host-wide credential (shared)'), ('host_login', 'Interactive host login (~/.claude)')], default='', help_text='Which credential the latest run actually used (personal vs. host-wide)', max_length=20),
        ),
        migrations.AddField(
            model_name='claudequeuejob',
            name='auth_user',
            field=models.ForeignKey(blank=True, help_text='User whose Claude credential this job runs on — the basis for per-user cost attribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claude_auth_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claudequeuejob',
            name='requested_auth_mode',
            field=models.CharField(choices=[('oauth', 'Max/Pro subscription (OAuth)'), ('api_key', 'Anthropic API key')], default='oauth', help_text='Auth mode requested for this job (frozen from the item at enqueue time)', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='claude_auth_mode',
            field=models.CharField(choices=[('oauth', 'Max/Pro subscription (OAuth)'), ('api_key', 'Anthropic API key')], default='oauth', help_text='Auth mode for Claude runs on this item: subscription (default) or pay-per-use API key', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='claude_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text="Personal Anthropic API key — runs jobs pay-per-use on this user's account"),
        ),
        migrations.AddField(
            model_name='user',
            name='claude_oauth_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text="Personal Claude Code OAuth token (`claude setup-token`) — runs jobs on this user's subscription"),
        ),
    ]
