# Generated by Django 5.2.15 on 2026-09-08 07:52

from django.conf import settings
from django.db import migrations, models


def assign_every_project_to_every_user(apps, schema_editor):
    """Backfill the new assignment so the visibility filter changes nothing yet.

    Without this, deploying #1248 would empty every list in the UserUI: the
    filter is strict (no assignment -> no projects), and no assignment exists
    before this migration runs. Starting from "everyone sees everything" keeps
    the switch behaviour-neutral and lets teams narrow the assignment project by
    project, at their own pace.
    """
    Project = apps.get_model('core', 'Project')
    User = apps.get_model('core', 'User')
    Membership = Project.members.through

    user_ids = list(User.objects.values_list('id', flat=True))
    if not user_ids:
        return

    Membership.objects.bulk_create(
        [
            Membership(project_id=project_id, user_id=user_id)
            for project_id in Project.objects.values_list('id', flat=True)
            for user_id in user_ids
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_user_mcp_token_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users for whom this project is relevant. Drives what the UserUI shows, not what a user is allowed to do.', related_name='visible_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            assign_every_project_to_every_user,
            # Reverse drops the whole table with the field, so nothing to undo.
            migrations.RunPython.noop,
        ),
    ]
