# Generated by Django 5.2.18 on 2026-10-06 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

_KNOWN_STATUSES = {
    'Inbox', 'Backlog', 'Working', 'Testing', 'Review', 'ReadyForRelease', 'Closed',
}


def backfill_from_activity(apps, schema_editor):
    """Seed the status history from existing 'item.status_changed' activities.

    The Activity log only covers transitions that called log_status_change(),
    so these rows are marked ``backfilled`` and treated as incomplete history.
    """
    Activity = apps.get_model('core', 'Activity')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Item = apps.get_model('core', 'Item')
    ItemStatusChange = apps.get_model('core', 'ItemStatusChange')

    try:
        item_ct = ContentType.objects.get(app_label='core', model='item')
    except ContentType.DoesNotExist:
        return

    item_ids = set(Item.objects.values_list('id', flat=True))
    rows = []
    activities = Activity.objects.filter(
        verb='item.status_changed', target_content_type=item_ct,
    ).values_list('target_object_id', 'summary', 'created_at', 'actor_id')
    for target_id, summary, created_at, actor_id in activities.iterator():
        if not summary.startswith('Status: ') or ' → ' not in summary:
            continue
        from_status, _, to_status = summary[len('Status: '):].partition(' → ')
        from_status, to_status = from_status.strip(), to_status.strip()
        if from_status not in _KNOWN_STATUSES or to_status not in _KNOWN_STATUSES:
            continue
        try:
            item_id = int(target_id)
        except (TypeError, ValueError):
            continue
        if item_id not in item_ids:
            continue
        rows.append(ItemStatusChange(
            item_id=item_id,
            from_status=from_status,
            to_status=to_status,
            changed_at=created_at,
            changed_by_id=actor_id,
            backfilled=True,
        ))
    ItemStatusChange.objects.bulk_create(rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0081_add_opus_5_5_sonnet_5_5_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                (
                    "changed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("backfilled", models.BooleanField(default=False)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="core.item",
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["to_status", "changed_at"],
                        name="core_itemst_to_stat_9aaca3_idx",
                    ),
                    models.Index(
                        fields=["item", "changed_at"],
                        name="core_itemst_item_id_857a49_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemStatusSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Inbox", "📥 Inbox"),
                            ("Backlog", "📋 Backlog"),
                            ("Working", "🚧 Working"),
                            ("Testing", "🧪 Testing"),
                            ("Review", "👀 Review"),
                            ("ReadyForRelease", "✅ Ready for Release"),
                            ("Closed", "✔ Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_snapshots",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "project", "status"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "project", "status"),
                        name="uniq_item_status_snapshot",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_from_activity, migrations.RunPython.noop),
    ]
