# Generated by Django 5.2.18 on 2026-10-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_item_status_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("Inbox", "📥 Inbox"),
                    ("Backlog", "📋 Backlog"),
                    ("Working", "🚧 Working"),
                    ("Testing", "🏁 Implemented"),
                    ("Review", "❓ Clarification"),
                    ("ReadyForRelease", "✅ Ready for Release"),
                    ("Closed", "✔ Closed"),
                ],
                default="Inbox",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itemstatussnapshot",
            name="status",
            field=models.CharField(
                choices=[
                    ("Inbox", "📥 Inbox"),
                    ("Backlog", "📋 Backlog"),
                    ("Working", "🚧 Working"),
                    ("Testing", "🏁 Implemented"),
                    ("Review", "❓ Clarification"),
                    ("ReadyForRelease", "✅ Ready for Release"),
                    ("Closed", "✔ Closed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mailactionmapping",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("Inbox", "📥 Inbox"),
                    ("Backlog", "📋 Backlog"),
                    ("Working", "🚧 Working"),
                    ("Testing", "🏁 Implemented"),
                    ("ReadyForRelease", "✅ Ready for Release"),
                    ("Closed", "✔ Closed"),
                ],
                help_text="Issue status for which this mapping applies (Review is not eligible for mail triggers)",
                max_length=20,
            ),
        ),
    ]
