from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/partials/in_progress_items/', views.dashboard_in_progress_items, name='dashboard-in-progress-items'),
    path('dashboard/partials/activity_stream/', views.dashboard_activity_stream, name='dashboard-activity-stream'),
    path('projects/', views.projects, name='projects'),
    path('projects/new/', views.project_create, name='project-create'),
    path('projects/<int:id>/', views.project_detail, name='project-detail'),
    path('projects/<int:id>/edit/', views.project_edit, name='project-edit'),
    path('projects/<int:id>/update/', views.project_update, name='project-update'),
    path('projects/<int:id>/delete/', views.project_delete, name='project-delete'),
    path('projects/<int:id>/clients/add/', views.project_add_client, name='project-add-client'),
    path('projects/<int:id>/clients/remove/', views.project_remove_client, name='project-remove-client'),
    path('projects/<int:id>/items/add/', views.project_add_item, name='project-add-item'),
    path('projects/<int:id>/nodes/add/', views.project_add_node, name='project-add-node'),
    path('projects/<int:id>/releases/add/', views.project_add_release, name='project-add-release'),
    path('projects/<int:id>/items/tab/', views.project_items_tab, name='project-items-tab'),
    path('projects/<int:id>/attachments/tab/', views.project_attachments_tab, name='project-attachments-tab'),
    path('projects/<int:id>/upload-attachment/', views.project_upload_attachment, name='project-upload-attachment'),
    path('projects/attachments/<int:attachment_id>/delete/', views.project_delete_attachment, name='project-delete-attachment'),
    path('projects/<int:id>/import-github-issues/', views.project_import_github_issues, name='project-import-github-issues'),
    path('items/inbox/', views.items_inbox, name='items-inbox'),
    path('items/backlog/', views.items_backlog, name='items-backlog'),
    path('items/working/', views.items_working, name='items-working'),
    path('items/testing/', views.items_testing, name='items-testing'),
    path('items/ready/', views.items_ready, name='items-ready'),
    path('items/new/', views.item_create, name='item-create'),
    path('items/<int:item_id>/', views.item_detail, name='item-detail'),
    path('items/<int:item_id>/edit/', views.item_edit, name='item-edit'),
    path('items/<int:item_id>/update/', views.item_update, name='item-update'),
    path('items/<int:item_id>/delete/', views.item_delete, name='item-delete'),
    path('items/<int:item_id>/classify/', views.item_classify, name='item-classify'),
    path('items/<int:item_id>/change-status/', views.item_change_status, name='item-change-status'),
    path('items/<int:item_id>/add-comment/', views.item_add_comment, name='item-add-comment'),
    path('items/comments/<int:comment_id>/update/', views.item_update_comment, name='item-update-comment'),
    path('items/comments/<int:comment_id>/delete/', views.item_delete_comment, name='item-delete-comment'),
    path('items/<int:item_id>/upload-attachment/', views.item_upload_attachment, name='item-upload-attachment'),
    path('items/attachments/<int:attachment_id>/delete/', views.item_delete_attachment, name='item-delete-attachment'),
    path('items/attachments/<int:attachment_id>/view/', views.item_view_attachment, name='item-view-attachment'),
    path('items/attachments/<int:attachment_id>/download/', views.item_download_attachment, name='item-download-attachment'),
    path('items/<int:item_id>/tabs/comments/', views.item_comments_tab, name='item-comments-tab'),
    path('items/<int:item_id>/tabs/attachments/', views.item_attachments_tab, name='item-attachments-tab'),
    path('items/<int:item_id>/tabs/activity/', views.item_activity_tab, name='item-activity-tab'),
    path('items/<int:item_id>/tabs/github/', views.item_github_tab, name='item-github-tab'),
    path('items/<int:item_id>/link-github/', views.item_link_github, name='item-link-github'),
    path('items/<int:item_id>/create-github-issue/', views.item_create_github_issue, name='item-create-github-issue'),
    path('items/<int:item_id>/ai/optimize-description/', views.item_optimize_description_ai, name='item-optimize-description-ai'),
    
    # AI endpoints
    path('ai/generate-title/', views.ai_generate_title, name='ai-generate-title'),
    path('ai/optimize-text/', views.ai_optimize_text, name='ai-optimize-text'),
    
    # Change Management URLs
    path('changes/', views.changes, name='changes'),
    path('changes/new/', views.change_create, name='change-create'),
    path('changes/<int:id>/', views.change_detail, name='change-detail'),
    path('changes/<int:id>/edit/', views.change_edit, name='change-edit'),
    path('changes/<int:id>/update/', views.change_update, name='change-update'),
    path('changes/<int:id>/delete/', views.change_delete, name='change-delete'),
    path('changes/<int:id>/approvers/add/', views.change_add_approver, name='change-add-approver'),
    path('changes/<int:id>/approvers/<int:approval_id>/remove/', views.change_remove_approver, name='change-remove-approver'),
    path('changes/<int:id>/approvals/<int:approval_id>/approve/', views.change_approve, name='change-approve'),
    path('changes/<int:id>/approvals/<int:approval_id>/reject/', views.change_reject, name='change-reject'),
    
    # Organisation URLs
    path('organisations/', views.organisations, name='organisations'),
    path('organisations/new/', views.organisation_create, name='organisation-create'),
    path('organisations/<int:id>/', views.organisation_detail, name='organisation-detail'),
    path('organisations/<int:id>/edit/', views.organisation_edit, name='organisation-edit'),
    path('organisations/<int:id>/update/', views.organisation_update, name='organisation-update'),
    path('organisations/<int:id>/delete/', views.organisation_delete, name='organisation-delete'),
    path('organisations/<int:id>/users/add/', views.organisation_add_user, name='organisation-add-user'),
    path('organisations/<int:id>/users/update/', views.organisation_update_user, name='organisation-update-user'),
    path('organisations/<int:id>/users/remove/', views.organisation_remove_user, name='organisation-remove-user'),
    path('organisations/<int:id>/projects/link/', views.organisation_link_project, name='organisation-link-project'),
    path('organisations/<int:id>/projects/unlink/', views.organisation_unlink_project, name='organisation-unlink-project'),
    
    # AI Provider URLs
    path('ai-providers/', views.ai_providers, name='ai-providers'),
    path('ai-providers/new/', views.ai_provider_create, name='ai-provider-create'),
    path('ai-providers/<int:id>/', views.ai_provider_detail, name='ai-provider-detail'),
    path('ai-providers/<int:id>/update/', views.ai_provider_update, name='ai-provider-update'),
    path('ai-providers/<int:id>/delete/', views.ai_provider_delete, name='ai-provider-delete'),
    path('ai-providers/<int:id>/get-api-key/', views.ai_provider_get_api_key, name='ai-provider-get-api-key'),
    path('ai-providers/<int:id>/fetch-models/', views.ai_provider_fetch_models, name='ai-provider-fetch-models'),
    path('ai-providers/<int:provider_id>/models/add/', views.ai_model_create, name='ai-model-create'),
    path('ai-providers/<int:provider_id>/models/<int:model_id>/update/', views.ai_model_update, name='ai-model-update'),
    path('ai-providers/<int:provider_id>/models/<int:model_id>/update-field/', views.ai_model_update_field, name='ai-model-update-field'),
    path('ai-providers/<int:provider_id>/models/<int:model_id>/toggle-active/', views.ai_model_toggle_active, name='ai-model-toggle-active'),
    path('ai-providers/<int:provider_id>/models/<int:model_id>/delete/', views.ai_model_delete, name='ai-model-delete'),
    
    # Agent URLs
    path('agents/', views.agents, name='agents'),
    path('agents/new/', views.agent_create, name='agent-create'),
    path('agents/<str:filename>/', views.agent_detail, name='agent-detail'),
    path('agents/<str:filename>/save/', views.agent_save, name='agent-save'),
    path('agents/save/', views.agent_create_save, name='agent-create-save'),
    path('agents/<str:filename>/delete/', views.agent_delete, name='agent-delete'),
    path('agents/<str:filename>/test/', views.agent_test, name='agent-test'),
    # AI Jobs History URLs
    path('ai-jobs-history/', views.ai_jobs_history, name='ai-jobs-history'),
    
    # Weaviate Sync URLs
    path('weaviate/status/<str:object_type>/<str:object_id>/', views.weaviate_status, name='weaviate-status'),
    path('weaviate/object/<str:object_type>/<str:object_id>/', views.weaviate_object, name='weaviate-object'),
    path('weaviate/push/<str:object_type>/<str:object_id>/', views.weaviate_push, name='weaviate-push'),
]
