from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('projects/', views.projects, name='projects'),
    path('projects/new/', views.project_create, name='project-create'),
    path('projects/<int:id>/', views.project_detail, name='project-detail'),
    path('projects/<int:id>/edit/', views.project_edit, name='project-edit'),
    path('projects/<int:id>/update/', views.project_update, name='project-update'),
    path('projects/<int:id>/delete/', views.project_delete, name='project-delete'),
    path('projects/<int:id>/clients/add/', views.project_add_client, name='project-add-client'),
    path('projects/<int:id>/clients/remove/', views.project_remove_client, name='project-remove-client'),
    path('projects/<int:id>/items/add/', views.project_add_item, name='project-add-item'),
    path('projects/<int:id>/nodes/add/', views.project_add_node, name='project-add-node'),
    path('projects/<int:id>/releases/add/', views.project_add_release, name='project-add-release'),
    path('items/inbox/', views.items_inbox, name='items-inbox'),
    path('items/backlog/', views.items_backlog, name='items-backlog'),
    path('items/working/', views.items_working, name='items-working'),
    path('items/testing/', views.items_testing, name='items-testing'),
    path('items/ready/', views.items_ready, name='items-ready'),
    path('items/new/', views.item_create, name='item-create'),
    path('items/<int:item_id>/', views.item_detail, name='item-detail'),
    path('items/<int:item_id>/edit/', views.item_edit, name='item-edit'),
    path('items/<int:item_id>/update/', views.item_update, name='item-update'),
    path('items/<int:item_id>/delete/', views.item_delete, name='item-delete'),
    path('items/<int:item_id>/classify/', views.item_classify, name='item-classify'),
    path('items/<int:item_id>/change-status/', views.item_change_status, name='item-change-status'),
    path('items/<int:item_id>/add-comment/', views.item_add_comment, name='item-add-comment'),
    path('items/<int:item_id>/upload-attachment/', views.item_upload_attachment, name='item-upload-attachment'),
    path('items/<int:item_id>/tabs/comments/', views.item_comments_tab, name='item-comments-tab'),
    path('items/<int:item_id>/tabs/attachments/', views.item_attachments_tab, name='item-attachments-tab'),
    path('items/<int:item_id>/tabs/activity/', views.item_activity_tab, name='item-activity-tab'),
    path('items/<int:item_id>/tabs/github/', views.item_github_tab, name='item-github-tab'),
    path('changes/', views.changes, name='changes'),
    
    # Organisation URLs
    path('organisations/', views.organisations, name='organisations'),
    path('organisations/new/', views.organisation_create, name='organisation-create'),
    path('organisations/<int:id>/', views.organisation_detail, name='organisation-detail'),
    path('organisations/<int:id>/edit/', views.organisation_edit, name='organisation-edit'),
    path('organisations/<int:id>/update/', views.organisation_update, name='organisation-update'),
    path('organisations/<int:id>/delete/', views.organisation_delete, name='organisation-delete'),
    path('organisations/<int:id>/users/add/', views.organisation_add_user, name='organisation-add-user'),
    path('organisations/<int:id>/users/update/', views.organisation_update_user, name='organisation-update-user'),
    path('organisations/<int:id>/users/remove/', views.organisation_remove_user, name='organisation-remove-user'),
    path('organisations/<int:id>/projects/link/', views.organisation_link_project, name='organisation-link-project'),
    path('organisations/<int:id>/projects/unlink/', views.organisation_unlink_project, name='organisation-unlink-project'),
    
    # AI Provider URLs
    path('ai-providers/', views.ai_providers, name='ai-providers'),
    path('ai-providers/new/', views.ai_provider_create, name='ai-provider-create'),
    path('ai-providers/<int:id>/', views.ai_provider_detail, name='ai-provider-detail'),
    path('ai-providers/<int:id>/update/', views.ai_provider_update, name='ai-provider-update'),
    path('ai-providers/<int:id>/delete/', views.ai_provider_delete, name='ai-provider-delete'),
    path('ai-providers/<int:id>/get-api-key/', views.ai_provider_get_api_key, name='ai-provider-get-api-key'),
    path('ai-providers/<int:id>/fetch-models/', views.ai_provider_fetch_models, name='ai-provider-fetch-models'),
    path('ai-providers/<int:provider_id>/models/add/', views.ai_model_create, name='ai-model-create'),
    path('ai-providers/<int:provider_id>/models/<int:model_id>/update/', views.ai_model_update, name='ai-model-update'),
    path('ai-providers/<int:provider_id>/models/<int:model_id>/delete/', views.ai_model_delete, name='ai-model-delete'),
]
