"""
Django settings for agira project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Logging directory setup - try /logs first, fallback to BASE_DIR/logs
LOG_BASE_PATH = Path('/logs')
LOG_DIR_AVAILABLE = False
try:
    LOG_BASE_PATH.mkdir(parents=True, exist_ok=True)
    LOG_DIR_AVAILABLE = True
except PermissionError:
    LOG_BASE_PATH = BASE_DIR / 'logs'
    try:
        LOG_BASE_PATH.mkdir(parents=True, exist_ok=True)
        LOG_DIR_AVAILABLE = True
        print(f'Warning: Using fallback log directory at {LOG_BASE_PATH}', file=sys.stderr)
    except PermissionError as e:
        print(f'Error: Cannot create log directory at {LOG_BASE_PATH}: {e}', file=sys.stderr)
        print('Logging to file will not be available', file=sys.stderr)
        LOG_DIR_AVAILABLE = False


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-zd-q-2@-+#(8wu#t=hsy2q236!1bh-pj0d*o5j9q*&%x*%975g')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,agira.angermeier.net,agira.isarlabs.de' ).split(',')
CSRF_TRUSTED_ORIGINS = [
    "https://agira.angermeier.net",
    "https://agira.isarlabs.de",
    "http://localhost:8005",
    "http://localhost:8006",
    "http://127.0.0.1"
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'django_tables2',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',                                                                                             
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'core.middleware.EmbedFrameMiddleware',  # Must come before XFrameOptionsMiddleware
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agira.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                'core.context_processors.open_github_issues_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'agira.wsgi.application'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,  # Cache darf nie die App killen
        },
        "KEY_PREFIX": "agira",
    }
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

db_engine = os.getenv('DB_ENGINE', 'django.db.backends.postgresql')

if db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': db_engine,
            'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': db_engine,
            'NAME': os.getenv('DB_NAME', 'agira'),
            'USER': os.getenv('DB_USER', 'agira_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'de-DE'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise configuration for serving static files in production
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Authentication URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Field encryption key for encrypted fields
# In production, this should be a long random string stored securely
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY', 'D_GzCwyVvkyI1o5qUh9rle_JPKAghlTxDGTfC3RRmB4=')

# Attachment Storage Configuration
AGIRA_DATA_DIR = BASE_DIR / os.getenv('AGIRA_DATA_DIR', 'data')
AGIRA_MAX_ATTACHMENT_SIZE_MB = int(os.getenv('AGIRA_MAX_ATTACHMENT_SIZE_MB', '25'))

# Cache configuration
# Using LocMemCache for simplicity and performance
# In production, consider Redis or Memcached for multi-server deployments
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'agira-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Redis Configuration for AI Agent Response Cache
REDIS_CACHE_ENABLED = os.getenv('REDIS_CACHE_ENABLED', 'False') == 'True'
REDIS_CACHE_HOST = os.getenv('REDIS_CACHE_HOST', 'localhost')
REDIS_CACHE_PORT = int(os.getenv('REDIS_CACHE_PORT', '6379'))
REDIS_CACHE_DB = int(os.getenv('REDIS_CACHE_DB', '0'))
REDIS_CACHE_PASSWORD = os.getenv('REDIS_CACHE_PASSWORD', None)
REDIS_CACHE_SOCKET_TIMEOUT = int(os.getenv('REDIS_CACHE_SOCKET_TIMEOUT', '5'))
REDIS_CACHE_SOCKET_CONNECT_TIMEOUT = int(os.getenv('REDIS_CACHE_SOCKET_CONNECT_TIMEOUT', '5'))

# Weaviate Search Configuration
WEAVIATE_SEARCH_LIMIT = int(os.getenv('WEAVIATE_SEARCH_LIMIT', '25'))
WEAVIATE_SEARCH_ALPHA = float(os.getenv('WEAVIATE_SEARCH_ALPHA', '0.5'))
WEAVIATE_SEARCH_MIN_QUERY_LENGTH = int(os.getenv('WEAVIATE_SEARCH_MIN_QUERY_LENGTH', '2'))

# Azure AD / MSAL Configuration
AZURE_AD_ENABLED = os.getenv('AZURE_AD_ENABLED', 'False') == 'True'
AZURE_AD_TENANT_ID = os.getenv('AZURE_AD_TENANT_ID', '')
AZURE_AD_CLIENT_ID = os.getenv('AZURE_AD_CLIENT_ID', '')
AZURE_AD_CLIENT_SECRET = os.getenv('AZURE_AD_CLIENT_SECRET', '')
AZURE_AD_REDIRECT_URI = os.getenv('AZURE_AD_REDIRECT_URI', 'http://localhost:8000/auth/azuread/callback/')
AZURE_AD_DEFAULT_ROLE = os.getenv('AZURE_AD_DEFAULT_ROLE', 'User')
AZURE_AD_SCOPES = ['User.Read', 'email']  # openid, profile, offline_access are reserved and added automatically by MSAL
AZURE_AD_AUTHORITY = f'https://login.microsoftonline.com/{AZURE_AD_TENANT_ID}' if AZURE_AD_TENANT_ID else ''

# django-tables2 configuration
DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5.html"

# Pagination settings
ITEMS_PER_PAGE = 25

# ============================================================================
# LOGGING CONFIGURATION
# Implements daily rotating file handler with 7-day retention
# ============================================================================
# Build handlers list based on LOG_DIR availability
logging_handlers_list = ['console_output']
if LOG_DIR_AVAILABLE:
    logging_handlers_list.insert(0, 'daily_rotating_file')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detailed_formatter': {
            'format': '[{levelname}] {asctime} {name} {module}.{funcName}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple_formatter': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console_output': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple_formatter',
        },
    },
    'root': {
        'handlers': logging_handlers_list,
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': logging_handlers_list,
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': logging_handlers_list,
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Add file handler only if log directory is available
if LOG_DIR_AVAILABLE:
    LOGGING['handlers']['daily_rotating_file'] = {
        'level': 'DEBUG',
        'class': 'logging.handlers.TimedRotatingFileHandler',
        'filename': str(LOG_BASE_PATH / 'app.log'),
        'when': 'midnight',
        'interval': 1,
        'backupCount': 7,
        'formatter': 'detailed_formatter',
        'encoding': 'utf-8',
    }

# ============================================================================
# SENTRY ERROR TRACKING CONFIGURATION
# Activated only when SENTRY_DSN environment variable is set
# ============================================================================
sentry_dsn_value = os.getenv('SENTRY_DSN', '').strip()
if sentry_dsn_value:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    
    # Parse traces_sample_rate with validation
    try:
        traces_rate = float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1'))
        if not 0.0 <= traces_rate <= 1.0:
            print(f'Warning: SENTRY_TRACES_SAMPLE_RATE={traces_rate} out of range [0.0, 1.0], using 0.1', file=sys.stderr)
            traces_rate = 0.1
    except (ValueError, TypeError):
        print(f'Warning: Invalid SENTRY_TRACES_SAMPLE_RATE value, using default 0.1', file=sys.stderr)
        traces_rate = 0.1
    
    # Parse send_default_pii with flexible boolean parsing
    send_pii_value = os.getenv('SENTRY_SEND_PII', '').lower()
    send_pii = send_pii_value in ('true', '1', 'yes', 'on')
    
    sentry_sdk.init(
        dsn=sentry_dsn_value,
        integrations=[DjangoIntegration()],
        traces_sample_rate=traces_rate,
        send_default_pii=send_pii,
        environment=os.getenv('SENTRY_ENVIRONMENT', 'production'),
    )

